---
# handlers file for python

- name: Get OS
  raw: cat /etc/*release | grep ^ID_LIKE= | tr -d "\n"
  register: os
#- debug: msg="os = {{ os }}"
#- debug: msg="os = {{ os.stdout }} oss= {{ os.stdout_lines }}"

- name: check /usr/bin/python
  raw: test -e /usr/bin/python
  register: python_is_absent
  ignore_errors: true
#- debug: msg="python_is_absent = {{ python_is_absent.rc }}"

- name: check /usr/bin/python3
  raw: test -e /usr/bin/python3
  register: python3_is_absent
  ignore_errors: true
  when: python_is_absent.rc == 1

- name: run apt update and install python
  raw: "{{ item }}"
  loop:
  - sudo apt update
  - sudo apt install -y python3-minimal
  become: true
  when: '"debian" in os.stdout and python_is_absent.rc == 1 and python3_is_absent.rc == 1'

- name: run yum install python
  raw: "{{ item }}"
  loop:
  - sudo yum -y install python3
  become: true
  when: '"rhel" in os.stdout and python_is_absent.rc == 1 and python3_is_absent.rc == 1'
  #when: python_is_absent.rc == 1 and python3_is_absent.rc == 1 and '"rhel" in os.stdout'
  #ignore_errors: true

- name: set symlink to python3
  raw: ln -s /usr/bin/python3 /usr/bin/python
  when: python_is_absent.rc == 1 #and python3_is_absent.rc == 0